version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true        # turn off security for local dev
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"

  log-uploader:
    image: python:3.11-slim
    container_name: log-uploader
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - INDEX_NAME=logs-zip-demo
      - LOGS_DIR=/logs
    working_dir: /app
    volumes:
      - ./uploader:/app
      - ./logs:/logs:ro
    command: >
      sh -c "pip install requests && python push_zip_folder_to_opensearch.py"

volumes:
  opensearch-data:
